[project]
name = "mlx-lora-demo"
version = "0.1.0"
description = "MLX LoRA fine-tuning demonstration"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "mlx-lm>=0.19.2",
    "sentencepiece>=0.1.99",
]

[tool.uv]
dev-dependencies = []
